// 남보석 포트폴리오 사이트 콘텐츠 (KO/EN). 게임 엔진은 game.js.
window.DATA = {
  meta: {
    name: { ko: '남보석', en: 'Bosuk Nam' },
    title: { ko: 'Backend Developer · Java / Spring', en: 'Backend Developer · Java / Spring' },
    email: 'popman90@naver.com',
    linkedin: 'https://www.linkedin.com/in/bosuk-nam-94018818a/',
    github: 'https://github.com/bosuknam',
    pdf: { ko: 'portfolio_ko.pdf', en: 'portfolio_en.pdf' },
  },

  ui: {
    ko: {
      start: '▶ 시작 (Enter)', pdfBtn: '📄 PDF 포트폴리오 (국문)', auto: '자동 진행', autoOn: '자동 진행 중', textMode: '📄 텍스트 이력서',
      inventory: '🎒 인벤토리 (I)', skip: '⏭ 끝으로', hint: '↑ 또는 클릭', hintTouch: '탭해서 보기',
      controls: '← → 이동 · ↑/Space 점프 · 물체 앞에서 ↑ 확인 · I 인벤토리',
      skills: '보유 스킬', achievements: '업적', locked: '???', collected: '획득', close: '닫기',
      world: 'WORLD', servers: '유휴서버 반납', coins: '스킬',
      goalTitle: 'STAGE CLEAR — 다음 스테이지를 찾는 중',
      goalBody: '여기까지 읽어주셔서 감사합니다. 대규모 인프라를 다루는 백엔드 개발자로서 다음 도전을 준비하고 있습니다.',
      download: 'PDF 포트폴리오 (국문)', downloadEn: 'PDF Portfolio (English)', contact: '이메일',
      idleTitle: '유휴 서버 회수 미니게임', idleBody: '졸고 있는 서버(💤)에 닿으면 반납됩니다. 실제로는 배치가 유휴를 판정하고 담당자 알림 → 조직장 결재 → 반납 순서로 돌아갑니다.',
      textResume: '텍스트 이력서', summary: '요약', career: '경력', projects: '프로젝트', education: '학력 · 자격', side: '사이드 프로젝트',
      newGame: '처음부터', resumeGame: '이어하기',
      dosHelp: '명령어: help, dir, whoami, skills, career, contact, win, cls, exit',
    },
    en: {
      start: '▶ Start (Enter)', pdfBtn: '📄 PDF Portfolio (English)', auto: 'Auto-play', autoOn: 'Auto-playing', textMode: '📄 Text resume',
      inventory: '🎒 Inventory (I)', skip: '⏭ Skip to end', hint: '↑ or click', hintTouch: 'Tap to open',
      controls: '← → move · ↑/Space jump · ↑ at an object to open · I inventory',
      skills: 'Skills', achievements: 'Achievements', locked: '???', collected: 'collected', close: 'Close',
      world: 'WORLD', servers: 'idle servers reclaimed', coins: 'skills',
      goalTitle: 'STAGE CLEAR — looking for the next stage',
      goalBody: 'Thanks for reading this far. I am a backend developer who builds systems for large-scale infrastructure, getting ready for the next challenge.',
      download: 'PDF Portfolio (English)', downloadEn: 'PDF 포트폴리오 (국문)', contact: 'Email',
      idleTitle: 'Idle Server Reclamation mini-game', idleBody: 'Touch a sleeping server (💤) to reclaim it. In real life a batch flags idle servers, notifies the owner, routes an org-lead approval, and then the server is returned.',
      textResume: 'Text resume', summary: 'Summary', career: 'Career', projects: 'Projects', education: 'Education · Certifications', side: 'Side projects',
      newGame: 'New game', resumeGame: 'Continue',
      dosHelp: 'Commands: help, dir, whoami, skills, career, contact, win, cls, exit',
    },
  },

  summary: {
    ko: ['대규모 인프라 자산을 다루는 사내 시스템을 설계부터 운영까지 end-to-end로 만드는 백엔드 개발자입니다.',
         '카카오에서 약 23만 대 서버(PM+VM), 4,000명 이상의 사용자를 대상으로 하는 서버 관리·유휴 서버 회수·전사 거버넌스 시스템을 4년 7개월간 개발·운영했습니다.',
         '유휴 서버 관리 시스템은 설계와 개발을 단독으로 리드했습니다.',
         'LG CNS에서는 자사 Spring 프레임워크(DevOn) 개발자로 금융권 MSA 프로젝트의 개발 환경·가이드·교육을 담당했습니다.',
         '반복 업무를 배치·알림·CI/CD로 자동화하는 데 강점이 있고, 최근에는 n8n과 Agentic AI를 일상 개발 워크플로우에 정착시키는 데 집중하고 있습니다.'],
    en: ['Backend developer who builds internal systems for large-scale infrastructure end-to-end, from design to operations.',
         'At Kakao I have spent 4 years 7 months developing and operating the server management, idle-server reclamation and company-wide governance systems covering ~230K servers and 4,000+ users.',
         'I led the design and implementation of the idle-server management system single-handedly.',
         'At LG CNS I was a framework developer on the in-house Spring framework (DevOn), owning dev environments, guides and training for MSA projects at major banks.',
         'I turn repetitive operations into batches, alerts and CI/CD, and currently focus on embedding n8n and agentic AI into the daily development loop.'],
  },

  // 스테이지: 왼→오 순서. 각 스테이지에 상호작용 오브젝트(card)와 코인(skill id)이 배치됨.
  stages: [
    { id: 'seoul', year: '1990', theme: 'dawn',
      title: { ko: '서울 출생', en: 'Born in Seoul' },
      card: { ko: ['1990년 서울에서 태어났습니다.', '4년 뒤, 아버지의 유학길을 따라 가족 모두 이스라엘로 떠납니다.'],
              en: ['Born in Seoul, 1990.', 'Four years later the whole family moved to Israel for my father\'s studies.'] },
      objects: [{ type: 'hospital', label: { ko: '1990 · 서울', en: '1990 · Seoul' } }] },

    { id: 'israel', year: '1994', theme: 'desert',
      title: { ko: '이스라엘에서 4년', en: 'Four years in Israel' },
      card: { ko: ['5살부터 4년 동안 이스라엘에서 살았습니다.', '말이 통하지 않아 놀림도 받았지만 11개월 만에 히브리어를 트게 됐고, 그때 얻은 끈기가 지금까지 남아 있습니다.', '"שלום" — 지금도 인사 정도는 합니다.'],
              en: ['Lived in Israel from age 5 for four years.', 'Couldn\'t speak a word at first; picked up Hebrew within 11 months. The persistence from that time has stuck with me.', '"שלום" — I can still say hello.'] },
      objects: [{ type: 'israel', label: { ko: '1994 · 이스라엘', en: '1994 · Israel' } }] },

    { id: 'pc', year: '1995', theme: 'room',
      title: { ko: '486 컴퓨터, DOS에서 Windows 3.1까지', en: '486 PC: from DOS to Windows 3.1' },
      dos: true,
      card: { ko: ['5살 때 처음 486 컴퓨터를 만졌습니다. C:\\> 프롬프트에서 시작해 Windows 3.1까지.', '초등학생 때는 플래시로 애니메이션을 만들며 "컴퓨터로 무언가를 만드는 일"을 좋아하게 됐습니다.', '아래 프롬프트에 명령어를 입력해보세요.', '<code>help · dir · whoami · skills · career · contact · win · cls · exit</code>'],
              en: ['First touched a 486 PC at five — starting from the C:\\> prompt up to Windows 3.1.', 'In elementary school I made Flash animations and learned I liked "making things with a computer".', 'Type a command in the prompt below.', '<code>help · dir · whoami · skills · career · contact · win · cls · exit</code>'] },
      objects: [{ type: 'pc', label: { ko: '486 · DOS / Win 3.1', en: '486 · DOS / Win 3.1' } }] },

    { id: 'univ', year: '2009', theme: 'campus',
      title: { ko: '한양대학교 도시공학과', en: 'Hanyang University, Urban Planning' },
      card: { ko: ['2009.03 – 2015.02 · 한양대학교 도시공학과 학사', '2011.05 – 2013.02 · 육군 병장 만기전역', '2014.05 · 도시계획기사 취득'],
              en: ['Mar 2009 – Feb 2015 · B.S. Urban Planning & Engineering, Hanyang University', 'May 2011 – Feb 2013 · Republic of Korea Army, sergeant', 'May 2014 · Engineer Urban Planning certificate'] },
      objects: [{ type: 'univ', label: { ko: '2009 · 한양대학교', en: '2009 · Hanyang Univ.' } }],
      achievements: ['urban'] },

    { id: 'kunhwa', year: '2015', theme: 'city',
      title: { ko: '(주)건화 · 도시계획부', en: 'Kunhwa Engineering · Urban Planner' },
      card: { ko: ['2015.01 – 2016.04 · 도시계획부 사원', '파주운정3지구 택지개발사업, 주안 2·4동 재정비촉진사업, 안양 도시·주거환경정비기본계획 등을 담당했습니다.', '일은 열심히 했지만 "이건 내 적성이 아니다"라는 생각을 매일 했습니다.'],
              en: ['Jan 2015 – Apr 2016 · Urban planner', 'Worked on the Paju Unjeong 3 district development, Juan 2·4-dong redevelopment, and Anyang urban maintenance master plan.', 'I worked hard, but every day I thought "this is not what I\'m meant to do."'] },
      objects: [{ type: 'office', color: '#8a94a6', sign: '건화', label: { ko: '2015 · (주)건화', en: '2015 · Kunhwa' } }] },

    { id: 'alphago', year: '2016', theme: 'night',
      title: { ko: '이세돌 vs 알파고', en: 'Lee Sedol vs AlphaGo' },
      card: { ko: ['2016년 3월, 회사 점심시간에 알파고가 이세돌을 이겼다는 뉴스를 봤습니다.', '무의식중에 나온 말: "개발자가 돼야겠네요."', '그해 4월 회사를 그만두고, 독학과 형의 과외로 프로그래밍을 시작했습니다.'],
              en: ['March 2016. Over lunch at work, the news said AlphaGo had beaten Lee Sedol.', 'What came out of my mouth: "I should become a developer."', 'I quit in April and started programming — self-study plus weekly lessons from my brother, a developer at Naver.'] },
      objects: [{ type: 'tv', label: { ko: '2016.03 · 알파고', en: '2016.03 · AlphaGo' } }] },

    { id: 'bootcamp', year: '2016', theme: 'dusk',
      title: { ko: '렉토피아 — 개발자 전향', en: 'Lectopia bootcamp — career change' },
      card: { ko: ['2016.05 – 2017.02 · C/C++ · 자료구조 · Java · Android · Spring', '응용 S/W 융합 프로젝트 과정 6개월: 스터디 플래너(StudyBugs), 이력서 도우미(RezoomIn), 명함 관리(BMW) 등을 팀으로 만들었습니다.', '프로그래밍이 언어보다 수학에 가깝다는 걸 깨닫고 나서는 정말 재미있어졌습니다.'],
              en: ['May 2016 – Feb 2017 · C/C++ · data structures · Java · Android · Spring', 'Six-month applied software project course: built a study planner (StudyBugs), a resume helper (RezoomIn) and a business-card manager (BMW) in teams.', 'Once I realized programming is closer to math than to language, it became genuinely fun.'] },
      objects: [{ type: 'school', label: { ko: '2016 · 렉토피아', en: '2016 · Lectopia' } }],
      coins: ['java', 'cpp'] },

    { id: 'tmax', year: '2017', theme: 'day',
      title: { ko: '티맥스소프트', en: 'TmaxSoft' },
      card: { ko: ['2017.04 – 2017.06 · 기술지원 (ProObject, AnyLink)', '첫 IT 회사. 3개월 뒤 LG CNS에 합격해 이직했습니다.'],
              en: ['Apr 2017 – Jun 2017 · Technical support (ProObject, AnyLink)', 'My first IT job. Left after three months when the LG CNS offer came.'] },
      objects: [{ type: 'office', color: '#3b6fd6', sign: 'Tmax', label: { ko: '2017 · 티맥스소프트', en: '2017 · TmaxSoft' } }] },

    { id: 'lgcns', year: '2017', theme: 'day', company: 'lgcns',
      title: { ko: 'LG CNS · 데브온솔루션팀 · 선임', en: 'LG CNS · DevOn Solution Team · Senior Engineer' },
      period: { ko: '2017.07 – 2022.03 (4년 9개월)', en: 'Jul 2017 – Mar 2022 (4y 9m)' },
      intro: { ko: '스마트팩토리 솔루션 개발자로 시작해 자사 Spring 프레임워크(DevOn) 개발팀으로 이동. 금융권 MSA 프로젝트의 F/W 개발자로 개발 환경·표준·교육을 담당했습니다. 신입사원 프로젝트 대상 수상, 사내 Java 강사.',
               en: 'Started as a smart-factory solution developer, moved to the in-house Spring framework (DevOn) team, and served as framework developer on banking MSA projects — owning dev environments, standards and training. New-hire project grand prize; internal Java instructor.' },
      objects: [{ type: 'tower', color: '#c8323c', sign: 'LG CNS', floors: 7, label: { ko: '2017–2022 · LG CNS', en: '2017–2022 · LG CNS' } }],
      coins: ['spring', 'mybatis', 'netty', 'kafka', 'jenkins'],
      achievements: ['instructor', 'award', 'ipe'],
      projects: [
        { n: { ko: '신한은행 SOL 신규 서비스 MSA', en: 'Shinhan Bank SOL New Services (MSA)' }, p: '2021.11 – 2022.03', r: { ko: 'F/W 개발자', en: 'Framework developer' },
          b: { ko: ['SOL 앱 내 야구·쿠폰·이벤트 기능을 MSA로 개발하는 프로젝트의 설계 단계 참여. 개발환경·가이드·교육·기술지원 담당', 'WebClient 기반 동기·비동기·병렬 호출(@Async, CompletableFuture) 모듈', 'Redis · RDBMS · Kafka 연동, Swagger, HyperCloud K8S'],
               en: ['Design phase of non-banking features (baseball, coupons, events) inside the SOL app as microservices; owned dev environment, guides, training, support', 'WebClient-based sync/async/parallel call module (@Async, CompletableFuture)', 'Redis · RDBMS · Kafka integration, Swagger, HyperCloud K8S'] } },
        { n: { ko: 'KB국민은행 청소년 전자지갑 MSA', en: 'KB Kookmin Bank Teen E-Wallet (MSA)' }, p: '2021.04 – 2021.11', r: { ko: 'F/W 개발자', en: 'Framework developer' },
          b: { ko: ['만 18세 미만 대상 충전식 전자지갑 앱. AWS 위 K8S/Docker MSA', 'JWT(Header ↔ Redis) 인증, LogAspect 로깅, Multiple Datasource', 'EAI 연동용 Netty 기반 TCP 통신 모듈', '이모지 저장 장애 → utf8mb4 + HikariCP 설정으로 해결'],
               en: ['Prepaid e-wallet app for users under 18; microservices on AWS with K8S/Docker', 'JWT (header ↔ Redis) auth, LogAspect logging, multiple datasources', 'Netty-based TCP module for EAI integration', 'Emoji storage incident fixed with utf8mb4 + HikariCP config'] } },
        { n: { ko: 'DevOn Framework / DevOn Boot 개발·기술지원', en: 'DevOn Framework / DevOn Boot' }, p: '2020.09 – 2022.03', r: { ko: 'F/W 개발자', en: 'Framework developer' },
          b: { ko: ['자사 Spring 프레임워크 기능 개발·버그 수정·릴리즈, 기술지원, 교육, 제안서', 'WebClient · JWT · Swagger2 · Netty(TCP) 모듈 추가, Maven → Gradle 전환', 'WebFlux REST · Thymeleaf · Spring Batch 템플릿, Jenkins → Nexus 릴리즈, Log4Shell 대응'],
               en: ['Feature development, bug fixes and releases for the in-house Spring framework; support, training, proposals', 'Added WebClient · JWT · Swagger2 · Netty(TCP) modules; migrated Maven → Gradle', 'WebFlux REST · Thymeleaf · Spring Batch templates; Jenkins → Nexus releases; Log4Shell response'] } },
        { n: { ko: 'MES Core 자산화 (공통 업무역량 상향 평준화)', en: 'MES Core Platform (LG group-wide)' }, p: '2020.04 – 2020.06', r: { ko: 'REST API 서버 구축', en: 'REST API server' },
          b: { ko: ['LG 전 계열사 공통 스마트팩토리 SPA 플랫폼', 'JWT 세션·사용자 관리, JPA로 MongoDB·MSSQL 연동, Solace pub-sub, BizActor Legacy 연동'],
               en: ['Group-wide smart-factory SPA platform', 'JWT session/user management; JPA with MongoDB & MSSQL; Solace pub-sub; BizActor legacy integration'] } },
        { n: { ko: 'iPharmMES HTML5 전환', en: 'iPharmMES HTML5 Migration' }, p: '2019.07 – 2020.09', r: { ko: 'Backend / Frontend', en: 'Backend / Frontend' },
          b: { ko: ['Silverlight 제약 MES → Spring Boot + JSP(MVC Model2)', 'Spring Security, SSO, 다국어, TLD 권한 태그, Silverlight ↔ JSP 하이브리드(iframe)'],
               en: ['Silverlight pharma MES → Spring Boot + JSP (MVC Model 2)', 'Spring Security, SSO, i18n, TLD permission tags, Silverlight ↔ JSP hybrid (iframe)'] } },
        { n: { ko: 'Industrial IoT Platform', en: 'Industrial IoT Platform' }, p: '2017.09 – 2018.12', r: { ko: 'Admin FE/BE · 현장 배포/운영', en: 'Admin FE/BE · on-site deployment' },
          b: { ko: ['공장 설비 데이터 대량 수집·관리 플랫폼 (Storm·Spark·HBase·Kafka·Redis·Node-red)', 'Kafka 실시간 수집 결과를 WebSocket으로 화면 반영, Admin(기기등록·제어·로그·화면디자이너)', 'LG Display 파주 · LG Chem 오창 · CJ대한통운 현장 배포·운영'],
               en: ['IIoT platform for high-volume factory data (Storm · Spark · HBase · Kafka · Redis · Node-red)', 'Real-time Kafka data to screens over WebSocket; admin UI (devices, control, logs, screen designer)', 'Deployed and operated at LG Display Paju, LG Chem Ochang, CJ Logistics'] } },
        { n: { ko: '신입사원 Java 사내강사', en: 'Internal Java Instructor' }, p: '2019.05 – 2019.08', r: { ko: '강사', en: 'Instructor' },
          b: { ko: ['JVM·컬렉션·예외·쓰레드·File IO 등 Java 전반 강의', '만족도 6.88 / 7.0 (SW Boot Camp), 6.90 / 7.0 (IT Career Start Technology)'],
               en: ['Java fundamentals: JVM, collections, exceptions, threads, file IO', 'Satisfaction 6.88 / 7.0 (SW Boot Camp), 6.90 / 7.0 (IT Career Start Technology)'] } },
      ] },

    { id: 'kakao', year: '2022', theme: 'kakao', company: 'kakao', idle: true,
      title: { ko: 'Kakao Corp · 인프라개발팀 · Backend Developer', en: 'Kakao Corp · Infra Development Team · Backend Developer' },
      period: { ko: '2022.03 – 현재 (4년 7개월)', en: 'Mar 2022 – Present (4y 7m)' },
      intro: { ko: '전사 인프라 자산(PM·VM·K8S·프로비전 서버 약 23만 대)을 관리하는 사내 시스템군의 백엔드를 개발·운영합니다. 본사 약 4,000명과 카카오엔터프라이즈·카카오모빌리티·AXZ 등 계열사 일부가 사용합니다.',
               en: 'Backend development and operations for the internal systems that manage Kakao\'s infrastructure assets — about 230K physical, virtual, K8S and provisioning servers. Used by ~4,000 people at HQ plus affiliates such as Kakao Enterprise, Kakao Mobility and AXZ.' },
      objects: [{ type: 'tower', color: '#f6c400', sign: 'kakao', floors: 9, dark: true, label: { ko: '2022– · Kakao', en: '2022– · Kakao' } }],
      coins: ['springbatch', 'k8s', 'docker', 'redis', 'mongo', 'promql', 'nodered', 'jpa', 'n8n', 'agent'],
      achievements: ['idle', 'slo', 'lead'],
      projects: [
        { n: { ko: '인프라 유휴 서버 관리 시스템', en: 'Infra Idle Server Management System' }, p: '2022.03 – ', r: { ko: '단독 리드 · 설계/개발/운영', en: 'Sole lead · design / build / operate' },
          b: { ko: ['배경: 23만 대 중 미사용·저사용 서버가 방치되어 비용 누수. 담당자 파악과 회수가 수작업', '전사 서버 Metric(PromQL) 동기화 배치로 유휴 판정 자동화. 주간 개인 알림 + 부서별 통계', '반납율 제고를 위한 조직장 결재 프로세스 설계·개발·도입 (2026)', 'Open API 키 발급 기반 외부 연동·사용자 관리 (JWT, Redis)', '시간·일·주 주기 배치 Cron 스케줄링, 모니터링 대시보드, 실패 알림 + SLO(3σ) 알림 (Node-RED)', 'K8S · Docker · SonarQube CI/CD'],
               en: ['Context: unused/under-used servers among 230K were leaking cost; owner lookup and reclamation were manual', 'Batch syncing company-wide metrics (PromQL) to automate idle detection; weekly personal alerts + department stats', 'Designed and built an org-lead approval process to raise the return rate (2026)', 'Open API key issuance for integration & user management (JWT, Redis)', 'Cron scheduling for hourly/daily/weekly batches, monitoring dashboard, failure + SLO (3σ) alerts (Node-RED)', 'CI/CD on K8S · Docker · SonarQube'] } },
        { n: { ko: '전사 거버넌스 시스템', en: 'Company-wide Governance System' }, p: '2025.02 – ', r: { ko: '설계 리딩 · 개발', en: 'Design lead · development' },
          b: { ko: ['전사 프로젝트·비용 대시보드, 담당자 관리 (Envers 변경 이력)', '프로젝트별 서버 매핑 동기화, 퇴사자 감지, 미결재 알림 배치 (RDBMS + MongoDB, JPA)', '반복 CS 업무를 WEB·API 기능으로 전환 — 대량 매핑 변경은 엑셀 업로드로, 상태는 실시간 확인', 'Open API 키 발급 기반 사용자 관리·통계, K8S · Docker · SonarQube CI/CD'],
               en: ['Company-wide project/cost dashboard and owner management (Envers change history)', 'Batches for per-project server mapping sync, resignee detection, pending-approval alerts (RDBMS + MongoDB, JPA)', 'Recurring CS work turned into web/API features — bulk mapping changes via Excel upload with real-time status', 'Open API key issuance for user management & stats; CI/CD on K8S · Docker · SonarQube'] } },
        { n: { ko: '인프라 서버 관리 시스템', en: 'Infra Server Management System' }, p: '2022.03 – 2025.04', r: { ko: '개발 · 운영', en: 'Development · operations' },
          b: { ko: ['본사·계열사 투입 서버 관리 시스템 (Web / REST API, MSA)', '서버 정합성 체크·알림 및 담당자 현행화 배치 (Spring Batch, Redis)', '장애대응 프로세스 가이드 작성 (Wiki), Jenkins · K8S · Docker · SonarQube CI/CD'],
               en: ['Server management system for HQ and affiliates (Web / REST API, MSA)', 'Server integrity check/alerting and owner-refresh batches (Spring Batch, Redis)', 'Incident response process guide (Wiki); CI/CD with Jenkins · K8S · Docker · SonarQube'] } },
        { n: { ko: '개발 생산성 · AI 자동화', en: 'Developer productivity · AI automation' }, p: '2025 – ', r: { ko: '매일 사용 중', en: 'Daily use' },
          b: { ko: ['Agentic AI 파이프라인: Jira 티켓 생성 → 구현 → AI 코드리뷰 → PR 작성 → 피드백 반영. 설계문서(Wiki/Discussion)·발표자료(HTML) 생성 루틴화', 'n8n: 사내 질의응답 봇, 실패 시 자동 재시도 등 장애 처리 자동화, 사이트 입력값 자동 채우기', '팀 워크플로우용 에이전트 Plugin / Skills 개발'],
               en: ['Agentic AI pipeline: Jira ticket → implementation → AI code review → PR → feedback; design docs (Wiki/Discussion) and HTML decks generated routinely', 'n8n: internal Q&A bot, failure handling with auto-retry, auto-filling internal sites', 'Agent plugins / skills for the team workflow'] } },
      ] },

    { id: 'goal', year: '2026', theme: 'sunrise', goal: true,
      title: { ko: '다음 스테이지', en: 'Next stage' },
      objects: [{ type: 'flag' }] },
  ],

  // 스킬(코인). cat: 인벤토리 그룹. lv: 1~5
  skills: {
    java:        { n: 'Java',            cat: 'lang',  lv: 5, ic: '☕' },
    cpp:         { n: 'C / C++',         cat: 'lang',  lv: 2, ic: '🔧' },
    spring:      { n: 'Spring Boot',     cat: 'back',  lv: 5, ic: '🍃' },
    springbatch: { n: 'Spring Batch',    cat: 'back',  lv: 5, ic: '⏱' },
    jpa:         { n: 'JPA / Envers',    cat: 'back',  lv: 4, ic: '🗂' },
    mybatis:     { n: 'MyBatis',         cat: 'back',  lv: 4, ic: '🧩' },
    netty:       { n: 'Netty',           cat: 'back',  lv: 3, ic: '🔌' },
    redis:       { n: 'Redis',           cat: 'data',  lv: 4, ic: '⚡' },
    mongo:       { n: 'MongoDB',         cat: 'data',  lv: 3, ic: '🍀' },
    mysql:       { n: 'MySQL / Oracle',  cat: 'data',  lv: 4, ic: '🐬' },
    kafka:       { n: 'Kafka',           cat: 'data',  lv: 3, ic: '📨' },
    k8s:         { n: 'Kubernetes',      cat: 'infra', lv: 4, ic: '☸' },
    docker:      { n: 'Docker',          cat: 'infra', lv: 4, ic: '🐳' },
    jenkins:     { n: 'Jenkins / ArgoCD',cat: 'infra', lv: 4, ic: '🤖' },
    promql:      { n: 'PromQL',          cat: 'infra', lv: 4, ic: '📈' },
    nodered:     { n: 'Node-RED',        cat: 'infra', lv: 4, ic: '🔴' },
    n8n:         { n: 'n8n',             cat: 'ai',    lv: 4, ic: '🕸' },
    agent:       { n: 'Agentic AI',      cat: 'ai',    lv: 4, ic: '🧠' },
  },
  skillCats: { lang: { ko: '언어', en: 'Language' }, back: { ko: '백엔드', en: 'Backend' }, data: { ko: '데이터', en: 'Data' }, infra: { ko: '인프라 / DevOps', en: 'Infra / DevOps' }, ai: { ko: 'AI / 자동화', en: 'AI / Automation' } },

  achievements: {
    urban:      { ic: '🏙', n: { ko: '도시계획기사', en: 'Engineer Urban Planning' }, d: { ko: '2014.05 · 개발자 이전의 자격증', en: 'May 2014 · from before the career change' } },
    award:      { ic: '🏆', n: { ko: '신입사원 프로젝트 대상', en: 'New-hire project grand prize' }, d: { ko: 'LG CNS 2017', en: 'LG CNS 2017' } },
    instructor: { ic: '🎓', n: { ko: 'Java 사내강사 6.9 / 7.0', en: 'Java instructor 6.9 / 7.0' }, d: { ko: '수강생 만족도 6.88 · 6.90', en: 'Satisfaction 6.88 · 6.90' } },
    ipe:        { ic: '📜', n: { ko: '정보처리기사', en: 'Engineer Information Processing' }, d: { ko: '2019.11', en: 'Nov 2019' } },
    idle:       { ic: '💤', n: { ko: '유휴 서버 시스템 단독 리드', en: 'Idle-server system, sole lead' }, d: { ko: '23만 대 서버 · 4,000+ 사용자', en: '230K servers · 4,000+ users' } },
    slo:        { ic: '📊', n: { ko: '배치 SLO 3σ 알림', en: 'Batch SLO 3σ alerting' }, d: { ko: '평균 대비 3σ 초과 시 자동 알림', en: 'Auto alert beyond mean + 3σ' } },
    lead:       { ko: null, ic: '🧭', n: { ko: '조직장 결재 프로세스 설계', en: 'Org-lead approval process' }, d: { ko: '반납율 제고 · 2026 도입', en: 'Raise return rate · rolled out 2026' } },
  },

  education: {
    ko: ['2009.03 – 2015.02 · 한양대학교 도시공학과 학사', '2014.05 · 도시계획기사', '2016.05 – 2017.02 · 렉토피아 응용 S/W 융합 프로젝트 과정', '2017.03 · TOEIC Speaking 170 (Lv.7)', '2018.08 · Neural Networks and Deep Learning — Coursera', '2019.11 · 정보처리기사'],
    en: ['2009 – 2015 · B.S. Urban Planning & Engineering, Hanyang University', 'May 2014 · Engineer Urban Planning', '2016 – 2017 · Applied Software Project Course, Lectopia', 'Mar 2017 · TOEIC Speaking 170 (Lv.7)', 'Aug 2018 · Neural Networks and Deep Learning — Coursera', 'Nov 2019 · Engineer Information Processing'],
  },
  sideProjects: [
    { n: 'lottery', l: 'Rust', u: 'https://github.com/bosuknam/lottery', d: { ko: '로또 당첨 이력을 분석해 번호 조합을 생성. 웹 버전 bosuknam.github.io/lottery', en: 'Generates lottery number combinations from historical draws. Web: bosuknam.github.io/lottery' } },
    { n: 'kis-trading', l: 'Python', u: 'https://github.com/bosuknam/kis-trading', d: { ko: '국내·해외 주식 동향과 지표 확인, 저평가 종목 매수를 돕는 앱', en: 'Stock trend/indicator tracker that helps buy undervalued stocks' } },
    { n: 'childcare-talk', l: 'Dart / Flutter', u: 'https://github.com/bosuknam/childcare-talk', d: { ko: '육아 대화 기록 모바일 앱', en: 'Mobile app for logging childcare conversations' } },
    { n: 'background-sound-app', l: 'JavaScript', u: 'https://github.com/bosuknam/background-sound-app', d: { ko: '상황별 배경음을 클릭 한 번으로 재생', en: 'One-click background sounds for different situations' } },
  ],
};
